# Generated by Django 5.2.7 on 2025-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield', models.CharField(choices=[('A', 'A_one'), ('B', 'B_two'), ('C', 'C_three'), ('D', 'D_four'), ('E', 'E_five')], default='A', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='shields',
            field=models.ManyToManyField(to='main_app.shield'),
        ),
    ]
