# Generated by Django 5.2.7 on 2025-10-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_shield_hero_shields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shield',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
