# Generated by Django 5.2.7 on 2025-10-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_shield_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shield', models.CharField(choices=[('W1', 'weapon1'), ('W2', 'weapon2'), ('W3', 'weapon3')], default='W1', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='shield',
            name='shield',
            field=models.CharField(choices=[('S1', 'Shield1'), ('S2', 'Shield2'), ('S3', 'Shield3')], default='S1', max_length=2),
        ),
        migrations.AddField(
            model_name='hero',
            name='weapons',
            field=models.ManyToManyField(to='main_app.weapon'),
        ),
    ]
