# Generated by Django 5.2.7 on 2025-10-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_weapon_alter_shield_shield_hero_weapons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='shield',
            new_name='weapon',
        ),
    ]
