# Generated by Django 5.2.7 on 2025-10-20 16:56

from django.db import migrations, models
from django.contrib.auth import get_user_model


User = get_user_model()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_shield_weapon_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='defense',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='strength',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='character',
            field=models.CharField(choices=[('A', 'Holy Paladin'), ('B', 'Primal Barbarian'), ('C', 'Dragon Knight')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='shield',
            name='shield',
            field=models.CharField(choices=[('S1', 'Oceans Defender'), ('S2', 'Skyward Kite'), ('S3', 'Earthguard Tower')], default='S1', max_length=2),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon',
            field=models.CharField(choices=[('W1', 'Natures Chopper'), ('W2', 'Fireborn Spear'), ('W3', 'Frostblade Claymore')], default='W1', max_length=2),
        ),
    ]

User = get_user_model()
for user in User.objects.all():
    print(user)
