# Generated by Django 5.2.7 on 2025-10-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_weapon_defense_weapon_speed_weapon_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shield',
            name='defense',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shield',
            name='speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shield',
            name='strength',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
