# Generated by Django 5.2.7 on 2025-10-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_shield_defense_shield_speed_shield_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='character',
            field=models.CharField(choices=[('A', 'Holy Paladin'), ('B', 'Primal Barbarian'), ('C', 'Dragon Knight'), ('D', 'Shadow Assassin'), ('E', 'Demon Hunter'), ('F', 'Chackie Jan'), ('G', 'Hasidic Warrior'), ('H', 'Mexican Vaquero'), ('I', 'Death Knight'), ('J', 'Every Italian Ever')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='shield',
            name='shield',
            field=models.CharField(choices=[('S1', 'Oceans Defender'), ('S2', 'Skyward Kite'), ('S3', 'Earthguard Tower'), ('S4', 'Aether Guard Shield'), ('S5', 'Correded Heater'), ('S6', 'Ironbound Wooden Shield'), ('S7', 'Leostrong Bastion'), ('S8', 'Mechanum Defender'), ('S9', 'Nightfeather Bulwark'), ('S10', 'Plainsteel Buckler'), ('S11', 'Serpentbloom Aegis'), ('S12', 'Bloodborn Edgeguard')], default='S1', max_length=3),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon',
            field=models.CharField(choices=[('W1', 'Natures Chopper'), ('W2', 'Fireborn Spear'), ('W3', 'Frostblade Claymore'), ('W4', 'Battleworn Hatchet'), ('W5', 'Common Broadsword'), ('W6', 'Forgebreak Polearm'), ('W7', 'Ironclad Shortblade'), ('W8', 'Nightslayers Scimitar'), ('W9', 'Plaugeringers Scythe'), ('W10', 'Shadowborn Blade'), ('W11', 'Shadowfeather Dagger'), ('W12', 'Solaris Glaive')], default='W1', max_length=3),
        ),
    ]
