# Generated by Django 5.2.7 on 2025-10-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_shield_defense_shield_speed_shield_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.hero')),
            ],
        ),
    ]
