# Generated by Django 5.2.7 on 2025-10-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_gold_hero_gold_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='amount',
            field=models.IntegerField(default=10),
        ),
    ]
