# Generated by Django 5.2.7 on 2025-10-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_hero_character_alter_shield_shield_and_more'),
        ('main_app', '0010_alter_gold_amount'),
    ]

    operations = [
    ]
