# Generated by Django 5.2.7 on 2025-10-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_gold_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shield',
            name='cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
