# Generated by Django 5.2.7 on 2025-10-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20251021_1732'),
        ('main_app', '0011_shield_cost_weapon_cost'),
    ]

    operations = [
    ]
