# Generated by Django 5.2.7 on 2025-10-26 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_winner', models.CharField(max_length=100)),
                ('hero_loser', models.CharField(max_length=100)),
                ('gold_change_winner', models.IntegerField(default=0)),
                ('gold_change_loser', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_initiated', to=settings.AUTH_USER_MODEL)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_lost', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
