# Generated by Django 5.2.7 on 2025-10-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_battlelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlelog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
