# Generated by Django 5.2.7 on 2025-10-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_battlelog_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlelog',
            name='hero_attacker',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
